---
spec-version: 0.30.0
name: ghc-build-analyzer
version: 0.1.0.0
github: MercuryTechnologies/ghc-build-analyzer
synopsis: Extract build timing data from GHC output
description: Please see the README on GitHub at
  <https://github.com/MercuryTechnologies/ghc-build-analyzer#readme>
category: Development
author:
  - Rebecca Turner <rebeccat@mercury.com>
  - Ian-Woo Kim <iank@mercury.com>
copyright: © 2022 Mercury Inc. All rights reserved.

default-extensions:
  # These are the extensions from GHC2021, pending GHC 9.2:
  - BangPatterns
  - BinaryLiterals
  - ConstrainedClassMethods
  - ConstraintKinds
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyCase
  - EmptyDataDecls
  - EmptyDataDeriving
  - ExistentialQuantification
  - ExplicitForAll
  - FlexibleContexts
  - FlexibleInstances
  - ForeignFunctionInterface
  - GADTSyntax
  - GeneralisedNewtypeDeriving
  - HexFloatLiterals
  - ImplicitPrelude
  - ImportQualifiedPost
  - InstanceSigs
  - KindSignatures
  - MonomorphismRestriction
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NamedWildCards
  - NumericUnderscores
  - PatternGuards
  - PolyKinds
  - PostfixOperators
  - RankNTypes
  - RelaxedPolyRec
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - StarIsType
  - TraditionalRecordSyntax
  - TupleSections
  - TypeApplications
  - TypeOperators
  - TypeSynonymInstances

    # Other language extensions:
  - OverloadedStrings
  - BlockArguments

dependencies:
  - base >= 4.15 && < 5
  - aeson
  - bytestring
  - text

ghc-options:
  - -Wall
  # - -ddump-json -dshow-passes

extra-source-files:
  - README.md

library:
  source-dirs: src
  dependencies:
    - containers
    - ghc == 9.2.*
    - transformers

executables:
  ghc-build-analyzer-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ghc-build-analyzer
      - optparse-applicative

tests:
  ghc-build-analyzer-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ghc-build-analyzer
