---
spec-version: 0.30.0
name: ghc-specter-daemon
version: 0.1.0.0
github: MercuryTechnologies/ghc-specter
synopsis: Daemon process for ghc-specter
description: Please see the README on GitHub at
  <https://github.com/MercuryTechnologies/ghc-specter#readme>
category: Development
author:
  - Rebecca Turner <rebeccat@mercury.com>
  - Ian-Woo Kim <iank@mercury.com>
copyright: © 2022 Mercury Inc. All rights reserved.

default-extensions:
  # These are the extensions from GHC2021, pending GHC 9.2:
  - BangPatterns
  - BinaryLiterals
  - ConstrainedClassMethods
  - ConstraintKinds
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyCase
  - EmptyDataDecls
  - EmptyDataDeriving
  - ExistentialQuantification
  - ExplicitForAll
  - FlexibleContexts
  - FlexibleInstances
  - ForeignFunctionInterface
  - GADTSyntax
  - GeneralisedNewtypeDeriving
  - HexFloatLiterals
  - ImplicitPrelude
  - ImportQualifiedPost
  - InstanceSigs
  - KindSignatures
  - MonomorphismRestriction
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NamedWildCards
  - NumericUnderscores
  - PatternGuards
  - PolyKinds
  - PostfixOperators
  - RankNTypes
  - RelaxedPolyRec
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - StarIsType
  - TraditionalRecordSyntax
  - TupleSections
  - TypeApplications
  - TypeOperators
  - TypeSynonymInstances

    # Other language extensions:
  - OverloadedStrings
  - BlockArguments

dependencies:
  - base >= 4.15 && < 5
  - aeson
  - bytestring
  - text

ghc-options:
  - -Wall

extra-source-files:
  - README.md

data-files:
  - assets/*.png

library:
  source-dirs: src
  dependencies:
    - OGDF
    - base64-bytestring
    - concur-core
    - concur-replica
    - containers
    - discrimination
    - errors
    - extra
    - fficxx-runtime
    - free
    - ghc
    - ghc-specter-plugin
    - hiedb
    - http-types
    - lens
    - optparse-applicative
    - replica
    - resourcet
    - scientific
    - stdcxx
    - stm
    - time
    - transformers
    - unliftio
    - wai
    - wai-websockets
    - warp
    - websockets

executables:
  ghc-specter-daemon:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - concur-core
      - concur-replica
      - containers
      - extra
      - ghc-specter-plugin
      - ghc-specter-daemon
      - lens
      - optparse-applicative
      - stm
      - time
      - transformers
      - yaml

tests:
  ghc-specter-daemon-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - containers
      - ghc-specter-daemon
      - ghc-specter-plugin
      - hspec
