name: "Build"
on: [pull_request, push]
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - compilerName: ghc942
            required: required
          - compilerName: ghc924
            required: required
      fail-fast: false
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - name: Install nix
      uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: enter-shell (GHC 9.4.2)
      run: |
        nix develop .#${{ matrix.compilerName }}
#  format:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/checkout@v2
#      # ormolu 0.3.0.1
#      - uses: mrkkrp/ormolu-action@v4