name: docs_pages_workflow

on:
  push:
    branches:
      - main

jobs:
  build_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Set up Python
        uses: actions/setup-python@5ccb29d8773c3f3f653e1705f474dfaa8a06a912 # v4.4.0
        with:
          python-version: 3.11.0
      - name: Install dependencies
        run: |
          python -m pip install -U sphinx
          python -m pip install sphinx-rtd-theme
          python -m pip install myst-parser
      - name: make the sphinx docs
        run: |
          make -C docs clean
          make -C docs html
      - name: Init new repo in dist folder and commit
        run: |
          cd docs/_build/html/
          git init
          touch .nojekyll
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'
      - name: Force push to destination branch
        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6 # v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./docs/_build/html
